version: '2.1'
services:
  appsvr:
    image: 38leinad/was-9
    ports:
     - "80:9080"
     - "9060:9060"
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - "./target/${artifactId}.war:/opt/IBM/WebSphere/AppServer/profiles/AppSrv01/monitoredDeployableApps/servers/server1/${artifactId}.war"
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:9080/${artifactId}/resources/health || exit 1
      interval: 5s
      timeout: 10s
      retries: 10